pipeline{
    agent any
    tools{
        nodejs "node 16.17.0"
    }

    stages{
        stage('Clonar Repositorio') {
            steps{
                checkout([$class:'GitSCM', branches:[[name:'*/main']], userRemoteConfigs:[[url:'https://github.com/ingegnereLiandi/MeuAppCi.git']]])
            }
        }

        stage('Instalar dependencias') {
            steps{
                bat "node -v"
                bat 'npm install'
                
            }
        }
        stage('Executar testes') {
            steps{
                
                bat 'npm run cy:run'  
                
                }
            }
        }
    }